version: "3.3"

services:

  rabbit_mq:
    image: rabbitmq:3.8-rc-management
    restart: always
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  db:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: Qwerty123
      POSTGRES_DB: postgres
    
    volumes:
      - pg_data:/var/lib/postgresql/data

  producer:
    build: producer
    depends_on:
        - rabbit_mq
        - db
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/app/producer

  consumer1:
    build: consumer
    depends_on:
        - rabbit_mq
        - db
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/app/consumer
  
  consumer2:
    build: consumer
    depends_on:
        - rabbit_mq
        - db
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/app/consumer

volumes:
    rabbit_mqdata:
      driver: local
    pg_data:
